// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// n2w_rcpp
arma::rowvec n2w_rcpp(arma::rowvec par, std::string hfun);
RcppExport SEXP hsltm_n2w_rcpp(SEXP parSEXP, SEXP hfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::string >::type hfun(hfunSEXP);
    __result = Rcpp::wrap(n2w_rcpp(par, hfun));
    return __result;
END_RCPP
}
// w2n_rcpp
arma::rowvec w2n_rcpp(arma::rowvec par, std::string hfun);
RcppExport SEXP hsltm_w2n_rcpp(SEXP parSEXP, SEXP hfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec >::type par(parSEXP);
    Rcpp::traits::input_parameter< std::string >::type hfun(hfunSEXP);
    __result = Rcpp::wrap(w2n_rcpp(par, hfun));
    return __result;
END_RCPP
}
// h_rcpp
double h_rcpp(double x, double y, arma::rowvec b, std::string hfun);
RcppExport SEXP hsltm_h_rcpp(SEXP xSEXP, SEXP ySEXP, SEXP bSEXP, SEXP hfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type b(bSEXP);
    Rcpp::traits::input_parameter< std::string >::type hfun(hfunSEXP);
    __result = Rcpp::wrap(h_rcpp(x, y, b, hfun));
    return __result;
END_RCPP
}
// gety_obs_rcpp
arma::vec gety_obs_rcpp(double x, bool null_yobs, double yobs, double ymax, double dy);
RcppExport SEXP hsltm_gety_obs_rcpp(SEXP xSEXP, SEXP null_yobsSEXP, SEXP yobsSEXP, SEXP ymaxSEXP, SEXP dySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type null_yobs(null_yobsSEXP);
    Rcpp::traits::input_parameter< double >::type yobs(yobsSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type dy(dySEXP);
    __result = Rcpp::wrap(gety_obs_rcpp(x, null_yobs, yobs, ymax, dy));
    return __result;
END_RCPP
}
// pxy_simple_rcpp
arma::vec pxy_simple_rcpp(arma::vec x, arma::vec y, std::string hfun, arma::rowvec b, arma::vec pcu, arma::mat Pi, arma::rowvec delta, double ymax, double dy, bool ally, bool cdf);
RcppExport SEXP hsltm_pxy_simple_rcpp(SEXP xSEXP, SEXP ySEXP, SEXP hfunSEXP, SEXP bSEXP, SEXP pcuSEXP, SEXP PiSEXP, SEXP deltaSEXP, SEXP ymaxSEXP, SEXP dySEXP, SEXP allySEXP, SEXP cdfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type hfun(hfunSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pcu(pcuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type dy(dySEXP);
    Rcpp::traits::input_parameter< bool >::type ally(allySEXP);
    Rcpp::traits::input_parameter< bool >::type cdf(cdfSEXP);
    __result = Rcpp::wrap(pxy_simple_rcpp(x, y, hfun, b, pcu, Pi, delta, ymax, dy, ally, cdf));
    return __result;
END_RCPP
}
// pxy_double_rccp
arma::vec pxy_double_rccp(arma::mat obs1, arma::mat obs2, std::string hfun, arma::rowvec b1, arma::rowvec b2, arma::vec pcu, arma::mat Pi, arma::rowvec delta, double ymax, double dy, bool ally, bool cdf);
RcppExport SEXP hsltm_pxy_double_rccp(SEXP obs1SEXP, SEXP obs2SEXP, SEXP hfunSEXP, SEXP b1SEXP, SEXP b2SEXP, SEXP pcuSEXP, SEXP PiSEXP, SEXP deltaSEXP, SEXP ymaxSEXP, SEXP dySEXP, SEXP allySEXP, SEXP cdfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type obs1(obs1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type obs2(obs2SEXP);
    Rcpp::traits::input_parameter< std::string >::type hfun(hfunSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type b1(b1SEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type b2(b2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pcu(pcuSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type dy(dySEXP);
    Rcpp::traits::input_parameter< bool >::type ally(allySEXP);
    Rcpp::traits::input_parameter< bool >::type cdf(cdfSEXP);
    __result = Rcpp::wrap(pxy_double_rccp(obs1, obs2, hfun, b1, b2, pcu, Pi, delta, ymax, dy, ally, cdf));
    return __result;
END_RCPP
}
