# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parameters transformation
#' 
#' Scale parameters from their "natural" interval to their "working" interval, 
#' the set of real numbers (for unconstrained optimization).
#' Written in C++.
#' 
#' @param par Parameters on their natural scale
#' @param hfun Name of hazard detection function
#' 
#' @return Unconstrained parameters (scaled to the set of real numbers)
#' 
#' @export
n2w_rcpp <- function(par, hfun) {
    .Call('hsltm_n2w_rcpp', PACKAGE = 'hsltm', par, hfun)
}

#' Parameters inverse transformation
#' 
#' Scale parameters back from the set of real numbers ("working" interval)
#' to their "natural" interval.
#' Written in C++.
#' 
#' @param par Unconstrained parameters (scaled to the set of real numbers)
#' @param hfun Name of hazard detection function
#' 
#' @return Parameters on their natural scale
#' 
#' @export
w2n_rcpp <- function(par, hfun) {
    .Call('hsltm_w2n_rcpp', PACKAGE = 'hsltm', par, hfun)
}

#' Hazard detection function
#' 
#' Used within the C++ code, and in the simulation function simData.
#' 
#' @param x Perpendicular distance of the detection
#' @param y Forward distance of the detection
#' @param b Parameters of the hazard function
#' @param hfun Name of hazard detection function
#' 
#' @return The value of the hazard function at (x,y)
#' 
#' @export
#' @importFrom Rcpp evalCpp
h_rcpp <- function(x, y, b, hfun) {
    .Call('hsltm_h_rcpp', PACKAGE = 'hsltm', x, y, b, hfun)
}

#' Forward distances in view
#' 
#' Computes all discrete forward distances in view. 
#' Written in C++.
#' 
#' @param x Perpendicular distance
#' @param null_yobs ???
#' @param yobs Forward distance
#' @param ymax Maximum forward distance in view
#' @param dy Forward distance step increment
#' 
#' @return A vector of the forward distances in view.
#' 
#' @export
gety_obs_rcpp <- function(x, null_yobs, yobs, ymax, dy) {
    .Call('hsltm_gety_obs_rcpp', PACKAGE = 'hsltm', x, null_yobs, yobs, ymax, dy)
}

#' Probability of detection (single observer)
#'
#' Calculate probability of detection at (x,y), or if cdf=TRUE, by (x,y), in the case
#' of a model with one observer.
#' Written in C++.
#'  
#' @param x Perpendicular distance.
#' @param y Forward distance.
#' @param hfun Hazard function name.
#' @param b Hazard function parameter vector.
#' @param pcu Bernoulli state-dependent probability parameters.
#' @param Pi Markov model transition probability matrix.
#' @param delta Markov model stationary distribution.
#' @param ymax Maximum forward distance in view.
#' @param dy Forward distance step increment.
#' @param ally Flag for whether or not to return probabilities at all forward distances in view.
#' @param cdf Flag for whether or not to return cumulative distribution function in forward dimension.
#' This differs from specifying ally=TRUE in that ally=TRUE calculates the cdf from ymax 
#' to y=0, whereas cdf=TRUE calculates the cdf from ymax to y.
#' 
#' @export
pxy_simple_rcpp <- function(x, y, hfun, b, pcu, Pi, delta, ymax, dy, ally, cdf) {
    .Call('hsltm_pxy_simple_rcpp', PACKAGE = 'hsltm', x, y, hfun, b, pcu, Pi, delta, ymax, dy, ally, cdf)
}

#' Probability of detection (double observer)
#'
#' Calculate probability of detection at (x,y), or if cdf=TRUE, by (x,y), in the case
#' of a model with two observers.
#' Written in C++.
#'  
#' @param x Matrix of perpendicular distances (two columns: one for each observer)
#' @param y Matrix of forward distances (two columns: one for each observer)
#' @param d Matrix of detections (two columns: one for each observer). d[i,j] is
#' 1 if observer j detected animal i, 0 otherwise.
#' @param hfun Hazard function name.
#' @param b1 Hazard function parameter vector of first observer.
#' @param b2 Hazard function parameter vector of second oberver.
#' @param pcu Bernoulli state-dependent probability parameters.
#' @param Pi Markov model transition probability matrix.
#' @param delta Markov model stationary distribution.
#' @param ymax Maximum forward distance in view.
#' @param dy Forward distance step increment.
#' @param ally Flag for whether or not to return probabilities at all forward distances in view.
#' @param cdf Flag for whether or not to return cumulative distribution function in forward dimension.
#' This differs from specifying ally=TRUE in that ally=TRUE calculates the cdf from ymax 
#' to y=0, whereas cdf=TRUE calculates the cdf from ymax to y.
#' 
#' @export
pxy_double_rccp <- function(x, y, d, hfun, b1, b2, pcu, Pi, delta, ymax, dy, ally, cdf) {
    .Call('hsltm_pxy_double_rccp', PACKAGE = 'hsltm', x, y, d, hfun, b1, b2, pcu, Pi, delta, ymax, dy, ally, cdf)
}

